proxy:
  build: proxy
  links:
    - etcd:etcd
  ports:
    - 80:80
    - 443:443
  volumes:
    - proxy/run.sh:/run.sh:ro
    - proxy/static/:/etc/nginx/static/default:ro
    - proxy/include/:/etc/nginx/include/default:ro
    - proxy/nginx.toml:/etc/confd/conf.d/nginx.toml:ro
    - proxy/nginx.conf:/etc/confd/templates/nginx.conf:ro
  environment:
    SITES: docker
    CLUSTER: local
    UPSTREAMS: app

app:
  build: test/app
  links:
    - etcd:etcd
  ports:
    - 3000
  environment:
    CLUSTER: local
    DOCKER_HOST: 192.168.59.103
    ETCD_URL: http://etcd:4001

site:
  build: test/site
  links:
    - etcd:etcd
  environment:
    VIRTUAL_HOST: docker
    ETCD_URL: http://etcd:4001

reg:
  build: reg
  links:
    - etcd:etcd
  environment:
    HOST: 192.168.59.103
    CLUSTER: local
    MAPPING: app:*_app_*:3000
    ETCD_URL: http://etcd:4001
    DOCKER_HOST: unix:///var/run/docker.sock
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

etcd:
  image: slintes/etcd:latest
  ports:
    - 4001:4001
    - 7001:7001