[template]
owner       = "nginx"
mode        = "0644"

src         = "/etc/confd/templates/nginx.conf.tmpl"
dest        = "/etc/nginx/nginx.conf"

check_cmd   = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd  = "/usr/sbin/service nginx reload"

prefix      = "/nginx"
keys        = [
  "/upstreams",
  "/services",
]