[template]
owner = "root"
group = "root"
mode = "0644"

src = "nginx.conf"
dest = "/etc/nginx/nginx.conf"

check_cmd = "/usr/sbin/nginx -t -c {{ .src }}"
reload_cmd = "/usr/sbin/service nginx reload"

prefix = "/nginx"
keys = [
  "/servers",
  "/sites"
]